git:
  depth: 1

language: go

go:
  - "1.10"

before_install:
  - go version
  - go env

script:
  # builds
  # Output is needed so that the file and directory names don't clash (both "aom")
  - go build -o aom/aom github.com/philippgille/apiomat-cli/aom
  # tests
  - echo todo
